[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/:splat/"
  status = 301
  force = false
  conditions = {Path = ["*[^/]"]}

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"
