[build]
  publish = "."

[[redirects]]
  from = "https://www.ccdoctor.co.kr/*"
  to = "https://ccdoctor.co.kr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/:splat/"
  status = 301
  force = false

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"
